
package rt;

import java.awt.Color;
/**
 *
 * @author ASUS
 */
public class mainmenu extends javax.swing.JFrame {


    public mainmenu() {
        initComponents();
        sensus.setText(masasensus());
        baru.setText(tambahan());
        hoho.setText(creator());
        butInfo.setBackground(Color.white);
        butPenduduk.setBackground(Color.white);
        butMenu.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sensus = new javax.swing.JLabel();
        hoho = new javax.swing.JLabel();
        butInfo = new javax.swing.JButton();
        butMenu = new javax.swing.JButton();
        butPenduduk = new javax.swing.JButton();
        baru = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sensus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        sensus.setText("jLabel2");
        getContentPane().add(sensus, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        hoho.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        hoho.setText("jLabel1");
        getContentPane().add(hoho, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, -1, -1));

        butInfo.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        butInfo.setText("INFO DESA");
        butInfo.setBorder(null);
        butInfo.setBorderPainted(false);
        butInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butInfoMouseExited(evt);
            }
        });
        butInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInfoActionPerformed(evt);
            }
        });
        getContentPane().add(butInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 430, 70));

        butMenu.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        butMenu.setText("LOGOUT");
        butMenu.setBorder(null);
        butMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butMenuMouseExited(evt);
            }
        });
        butMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMenuActionPerformed(evt);
            }
        });
        getContentPane().add(butMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 430, 70));

        butPenduduk.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        butPenduduk.setText("data penduduk");
        butPenduduk.setBorder(null);
        butPenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butPendudukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butPendudukMouseExited(evt);
            }
        });
        butPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPendudukActionPerformed(evt);
            }
        });
        getContentPane().add(butPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 430, 70));
        //butPenduduk.setOpaque(false);
        //butPenduduk.setContentAreaFilled(false);
        //butPenduduk.setBorderPainted(false);

        baru.setText("jLabel1");
        getContentPane().add(baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fixMain.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMenuActionPerformed
        new login().show();
        this.dispose();
    }//GEN-LAST:event_butMenuActionPerformed

    private void butInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInfoActionPerformed
        new Info().show();
        this.dispose();
    }//GEN-LAST:event_butInfoActionPerformed

    private void butPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPendudukActionPerformed
        new Menu().show();
        this.dispose();
    }//GEN-LAST:event_butPendudukActionPerformed

    private void butInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butInfoMouseEntered
        // TODO add your handling code here:
        butInfo.setBackground(Color.gray);
    }//GEN-LAST:event_butInfoMouseEntered

    private void butInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butInfoMouseExited
        // TODO add your handling code here:
        butInfo.setBackground(Color.white);
    }//GEN-LAST:event_butInfoMouseExited

    private void butPendudukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butPendudukMouseEntered
        // TODO add your handling code here:
        butPenduduk.setBackground(Color.gray);
    }//GEN-LAST:event_butPendudukMouseEntered

    private void butPendudukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butPendudukMouseExited
        // TODO add your handling code here:
        butPenduduk.setBackground(Color.white);
    }//GEN-LAST:event_butPendudukMouseExited

    private void butMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMenuMouseEntered
        // TODO add your handling code here:
        butMenu.setBackground(Color.gray);
    }//GEN-LAST:event_butMenuMouseEntered

    private void butMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMenuMouseExited
        // TODO add your handling code here:
        butMenu.setBackground(Color.white);
    }//GEN-LAST:event_butMenuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baru;
    private javax.swing.JButton butInfo;
    private javax.swing.JButton butMenu;
    private javax.swing.JButton butPenduduk;
    private javax.swing.JLabel hoho;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel sensus;
    // End of variables declaration//GEN-END:variables


    String masasensus(){
            implementasi2 implementasi = new implementasi2();

            return implementasi.sensus();
        }
    String tambahan(){
        quotes baru = new quotes();
        return baru.penduduk();
    }
    
    static String creator(){
        return "Created by: Michael Arselius Pamasi.";
    }
}